// Generated by LiveScript 1.6.0
(function(){
  var parseMethod, parsePlugin, plugins, result, i$, len$, plugin;
  parseMethod = function(node){
    var result, i$, ref$, len$, child;
    result = '';
    for (i$ = 0, len$ = (ref$ = node.children).length; i$ < len$; ++i$) {
      child = ref$[i$];
      switch (child.nodeName) {
      case 'OUTPUT':
        result += '        System.out.println(' + child.innerHtml + ');\n';
        break;
      default:
        result = 'Unexpected token ' + child.nodeName;
      }
    }
    return result;
  };
  parsePlugin = function(node){
    var result, i$, ref$, len$, child;
    result = '';
    for (i$ = 0, len$ = (ref$ = node.children).length; i$ < len$; ++i$) {
      child = ref$[i$];
      switch (child.nodeName) {
      case 'ONENABLE':
        result += '    public function onEnable()\n    {\n' + parseMethod(child) + '    }\n';
        break;
      default:
        result = 'Unexpected token ' + child.nodeName;
      }
    }
    return result;
  };
  plugins = document.getElementsByTagName('plugin');
  result = '<pre>';
  for (i$ = 0, len$ = plugins.length; i$ < len$; ++i$) {
    plugin = plugins[i$];
    result += 'public class Main extends Javaplugin\n{\n' + parsePlugin(plugin) + '}</pre>';
  }
  document.write(result);
}).call(this);
